### PR TITLE
Fix reflect

### LINKED ISSUE #15: Incorrect definition for `reflect` method
`Promise.reflect()` returns a `Promise<PromiseInspection>`, but the current definition has it returning just a `PromiseInspection`. 

See the conversation [here](https://github.com/typed-typings/npm-bluebird/pull/10#issuecomment-221582977)

### PR DESCRIPTION
**Pull request by unional**
Fix #15

### CODE REVIEW

File: bluebird.d.ts [hunk 1]
```diff
@@ -124,7 +124,8 @@ declare class Bluebird<R> implements Bluebird.Thenable<R>, Bluebird.Inspection<R
    * Synchronously inspect the state of this `promise`. The `PromiseInspection` will represent the state of
    * the promise as snapshotted at the time of calling `.reflect()`.
    */
-  reflect(): Bluebird.Inspection<R>;
+  reflect(): Bluebird<Bluebird.Inspection<R>>;
+  reflect(): Bluebird<Bluebird.Inspection<any>>;
```
Comment (louy) [inline bluebird.d.ts:128]: I don't think we'll ever use the second overload in this case unless someone explicitly casts it, so we probably don't need it.
